- name: Product Strategy Consulting
  icon: fa-desktop
  description: Assist companies in defining and refining their product (web and mobile native apps) strategy to align with business objectives. Offer insights into market trends, competitive landscapes, and potential opportunities for innovation.

- name: Team Leadership and Development
  icon: fa-code
  description: Provide leadership training and guidance to product development and engineering teams. Implement strategies to enhance team collaboration, productivity, and innovation.

- name: Innovation Workshops
  icon: fa-lightbulb
  description: Conduct workshops to stimulate and capture innovative ideas within the organization. Facilitate sessions focused on fostering a culture of creativity and continuous improvement.

- name: Technical Architecture Review
  icon: fa-compass
  description: Conduct technical architecture reviews to ensure scalability, security, and efficiency of software systems. Offer recommendations for optimising technical infrastructures.

- name: Data-Driven Decision Making
  icon: fa-chart-line
  description: Implement data analytics frameworks to inform product decisions and measure performance. Advise on key performance indicators (KPIs) and metrics relevant to product success.

- name: Agile Transformation
  icon: fa-clock
  description: Assist companies in adopting agile methodologies for more efficient and adaptive product development. Facilitate agile training sessions and guide teams through the agile transformation process.
